<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Delete</name>
   <tag></tag>
   <elementGuidId>281b81ba-9947-4e8f-8c26-d2d54b23158a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div/eproc-basket-contents/div/div/div[2]/div/div/a[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div/eproc-basket-contents/div/div/div[2]/div/div/a[3]</value>
   </webElementProperties>
</WebElementEntity>
