<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CheckboxFifthItem</name>
   <tag></tag>
   <elementGuidId>29771f34-751f-4b45-b154-552a246dbf41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='items-in-catalogs']/eproc-product-list/dew-card/dew-flex/dew-flex-item[5]/eproc-product-card/dew-card/dew-row/dew-col[1]/div</value>
   </webElementProperties>
</WebElementEntity>
