<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CartIcon</name>
   <tag></tag>
   <elementGuidId>1742cf48-d793-4257-8d2b-6a20146b0f0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//eproc-spotlight/div[2]/div/div/eproc-cart-spotlight/div/div/span</value>
   </webElementProperties>
</WebElementEntity>
