<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MyRequisitionTab</name>
   <tag></tag>
   <elementGuidId>596f0542-26c0-4258-998b-978e698753ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='spyTab1']/dew-section/div/dew-section-body/dew-tabset/div/div[1]/div/div/ul/li[1]/a</value>
   </webElementProperties>
</WebElementEntity>
