<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BusinessUnit</name>
   <tag></tag>
   <elementGuidId>f1936e1a-742b-485b-98f4-8636ccc9bc13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='my-baskets']/dew-row/dew-col[1]/eproc-basket-card/dew-card/dew-card-body/div/eproc-share-basket-dialog/dew-modal[1]/div/div/div[2]/dew-modal-body/dew-row/dew-col/dew-select/dew-dropdown/div/div[2]/div/div[3]</value>
   </webElementProperties>
</WebElementEntity>
