<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GridViewButton</name>
   <tag></tag>
   <elementGuidId>06a60191-7d27-49e8-bb30-9d002579dbee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//dew-btn-group/dew-btn[2]/button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
