<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BasketNameInputBox</name>
   <tag></tag>
   <elementGuidId>b189774a-a96f-4f60-bf77-4604a1fb73b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//eproc-add-to-basket-modal/dew-modal/div/div/div[2]/dew-modal-body/div[2]/div/input</value>
   </webElementProperties>
</WebElementEntity>
