<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ButtonAddToBasket</name>
   <tag></tag>
   <elementGuidId>dbf00841-44ba-4bfa-b41f-c3913d80562c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//eproc-add-to-basket-modal/dew-modal/div/div/div[3]/dew-modal-footer/dew-btn/button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//eproc-add-to-basket-modal/dew-modal/div/div/div[3]/dew-modal-footer/dew-btn/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
