<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SearchAndSelectBox</name>
   <tag></tag>
   <elementGuidId>81cf3f62-a3bd-4ec5-91e1-b91dbcff2d19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//eproc-add-to-basket-modal/dew-modal/div/div/div[2]/dew-modal-body/div[2]/div/dew-typeahead/div/div[1]/input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//dew-typeahead/div/div[1]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
