<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PunchoutsTab</name>
   <tag></tag>
   <elementGuidId>6d3a286f-f2ca-4d01-8888-eb121a373096</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//eproc-online-store/dew-tabset/div/div[1]/div/div/ul/li[3]/a</value>
   </webElementProperties>
</WebElementEntity>
