<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BasketFavoriteIcon</name>
   <tag></tag>
   <elementGuidId>4cd606ff-1708-4e4f-89eb-9e6fc2c5acec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='all-baskets']/dew-row/dew-col[1]/eproc-basket-card/dew-card/dew-card-body/dew-flex/dew-flex-item[2]/dew-icon</value>
   </webElementProperties>
</WebElementEntity>
