<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CheckBox</name>
   <tag></tag>
   <elementGuidId>c37b42a4-2690-4652-9913-384393185358</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//eproc-basket-contents/div/dew-block/dew-row/dew-col[1]/eproc-product-card/dew-card/dew-row/dew-col[1]/div</value>
   </webElementProperties>
</WebElementEntity>
