<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FavoriteIcon</name>
   <tag></tag>
   <elementGuidId>985b19a9-cac8-4c3a-a2d5-779259d79aee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//dew-row/dew-col[1]/eproc-product-card/dew-card/dew-row/dew-col[3]/dew-row[1]/dew-col[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//dew-row/dew-col[1]/eproc-product-card/dew-card/dew-row/dew-col[3]/dew-row[1]/dew-col[2]/div</value>
   </webElementProperties>
</WebElementEntity>
