<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Home</name>
   <tag></tag>
   <elementGuidId>7b114de9-c5cb-4e09-b63b-1d74c7016c2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//dew-breadcrumb/ol/li[1]/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
