<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SerachBox</name>
   <tag></tag>
   <elementGuidId>1dd94b09-4288-42f0-922f-466f8cc0fce7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//eproc-online-store/eproc-spotlight/div[2]/div/div/div[2]/div/eproc-main-search/div[1]/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
