<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ActionButton</name>
   <tag></tag>
   <elementGuidId>15bb0bee-e9e5-4020-964c-e1ffc1065baa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//eproc-basket-contents/div/div/div[2]/div/dew-icon</value>
   </webElementProperties>
</WebElementEntity>
