<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Delete</name>
   <tag></tag>
   <elementGuidId>bdd3e034-95a5-474b-b583-2ce9c211d477</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>eproc-basket-contents/div/div/div[2]/div/div/a[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//eproc-basket-contents/div/div/div[2]/div/div/a[3]</value>
   </webElementProperties>
</WebElementEntity>
