<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>YesButton</name>
   <tag></tag>
   <elementGuidId>7a27e060-7891-4b49-bc9c-b7c044918cb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='all-baskets']/dew-row/dew-col[1]/eproc-basket-card/dew-card/dew-card-body/div/dew-modal/div/div/div[3]/dew-modal-footer/dew-btn[2]/button</value>
   </webElementProperties>
</WebElementEntity>
