<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Taxes</name>
   <tag></tag>
   <elementGuidId>560358c3-dd9f-4039-84ba-66345df6e91f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//th[text()='Taxes']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
